config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'packages', to: 'pages#packages'
  get 'login', to: 'pages#login'
  resources :contacts
  get 'quote', to: 'contacts#new'
end

#Add new pages here

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :website, presence: true
  validates :timeline, presence: true
  validates :comments, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to new_contact_path, notice:  "Submitted successfully."
    else
      redirect_to new_contact_path, alert:  "An error occured."
    end
  end
  
  private
    def contact_params
      params.require(:contact).permit(:name, :email, :website, :timeline, :budget, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
  
  def login
  end
  
  def packages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "alert alert-success"
    when :alert then "alert alert-danger"
    end
  end
end

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Free Quote</h1>
    <br>
    <div class="quote-form">
      <div class="well">
        <%= form_for @contact do |f| %>
        
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :website %>
            <%= f.text_field :website, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :timeline %>
            <%= f.text_field :timeline, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :budget %><br> 
            <%= f.select("budget", ['$500 - $1,000', '$1,000 - $2,500', '$2,500 - $5,000', '$5,000 - $10,000', '$10,000+']) %>
          </div>
            
          <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class: 'form-control' %>
          </div> 
    
            <%= f.submit 'Submit', class: 'btn btn-info' %>
           
          <div class="message">
            <%= render 'layouts/flash_message' %>
          </div>
        
          <h6>* all fields required</h6>
        
        <% end %>
      </div>
    </div>
  </div>
    
  <div class="col-md-4">test</div>


</div>
    

app/views/layouts/_flash_message.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %>
  </div>
<% end %>
  
<% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Bo Blacha</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body> 
    <div id="wrapper">
      <div class="top-bar">
        <header>Bo Blacha</header>
      </div>
      
      <div class="nav-bar">
        <ul class="header-subnav">
          <li><%= link_to "HOME", root_path %></li>
          <li><%= link_to "ABOUT", about_path %></li>
          <li><%= link_to "PACKAGES", packages_path %></li>
          <li><%= link_to "FREE QUOTE", quote_path %></li>
          <li><%= link_to "LOGIN", login_path %></li>
        </ul>
      </div>
      
      <div class="container">
        <%= yield %>
      </div>
      
      <div class="foot">
        <footer class="footer">
          <p class="copyr"><a id="copyright"></a>shite design © 2017 Bo Blacha</p>
        </footer>
    	</div>
      
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

<br/>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-md-8">
  <h1>Welcome to the home page.</h1>
  
  <br/>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam,
  nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!
  
  orem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!
  
  orem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!

  
  <p>
    <a id="news"></a><h1>News</h1>
  </p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!</p>
  
  </div>
  
  <div class="col-md-4"><br>
    <div class="query-box">test<br>
    <br><br><br>
    </div>
   <br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!
 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, illo, magnam, nam quaerat beatae laborum ab dicta nobis asperiores aspernatur aliquam rerum laudantium nihil possimus veritatis error obcaecati sunt animi!

  </div>
</div>

app/views/pages/login.html.erb
<%= stylesheet_link_tag "login" %>

<h1>Login</h1>

<br/>
<br/>

app/views/pages/packages.html.erb
<%= stylesheet_link_tag "packages" %>

<div class="headtitle">
    <h1>Packages</h1>
</div>

<div id="packages">
  <div class="row">
    <div class="col-sm-4">
      <ul class="pricing-column">
        <li class="title">Basic</li>
        <li class="price">$49.99</li>
        <li class="description">Description</li>
        <li class="description">5 Potatoes</li>
        <li class="description">10 Apples</li>
        <li class="description">40 Users</li>
        <li class="description">25GB Storage</li>
        <li><a class="btn btn-default" href="./">Buy Now</a></li>
      </ul>
      </div>
        
    <div class="col-sm-4">
      <ul class="pricing-column">
        <li class="title">Standard</li>
        <li class="price">$99.99</li>
        <li class="description">Description</li>
        <li class="description">5 Potatoes</li>
        <li class="description">10 Apples</li>
        <li class="description">40 Users</li>
        <li class="description">25GB Storage</li>
        <li><a class="btn btn-info" href="./">Buy Now</a></li>
      </ul>
      </div>
        
    <div class="col-sm-4">  
      <ul class="pricing-column">
        <li class="title">Premium</li>
        <li class="price">$199.99</li>
        <li class="description">Description</li>
        <li class="description">5 Potatoes</li>
        <li class="description">10 Apples</li>
        <li class="description">40 Users</li>
        <li class="description">25GB Storage</li>
        <li><a class="btn btn-primary" href="./">Buy Now</a></li>
      </ul>
    </div>
  </div>
</div>

<br/><br/><br/><br/><br/><br/>